---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: consul_template_install_flag

- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
  when: consul_template_configure_flag
