---
# install ansible packages
# ansible-pull is used during final machine configuration
- name: Install ansible prerequsities
  ansible.builtin.apt:
    name: [git, python3-netaddr, software-properties-common]
    state: present

- name: Install ansible client install via apt
  ansible.builtin.apt:
    name: ansible
    state: present
  when: ansible_install_from_apt

- name: Remove ansible client install via apt
  ansible.builtin.apt:
    name: ansible
    state: present
  when: not ansible_install_from_apt

- name: Create virtualenv for ansible
  ansible.builtin.command:
    cmd: "python3 -m venv /opt/ansible-venv"
    creates: /opt/ansible-venv/bin/python
  when: ansible_install_from_pip

- name: Install ansible in virtualenv
  ansible.builtin.command:
    cmd: "/opt/ansible-venv/bin/pip install ansible==9.0.1"
  when: ansible_install_from_pip

- name: Symlink ansible binaries to /usr/local/bin
  ansible.builtin.file:
    src: "/opt/ansible-venv/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - ansible
    - ansible-pull
    - ansible-playbook
    - ansible-galaxy
  when: ansible_install_from_pip

- name: Perform ansible client install cleanup via pip
  ansible.builtin.file:
    path: /opt/ansible-venv
    state: absent
  when: not ansible_install_from_pip
